config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tasks#index"

  resources :tasks do
    post "mark_task_as_done", as: "complete", on: :member
    collection do
      get "export_csv"
      get "export_csv_form"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  has_rich_text :description

  validates :title, :due_date, presence: true
  validates_inclusion_of :status, in: [true, false]
  validates :title, length: {minimum: 3}
  validates :description, length: {maximum: 250}

  scope :completed, -> { where(status: true) }
  scope :incomplete, -> { where(status: false) }
  default_scope { order(created_at: :desc) }

  def completed?
    status == true
  end

  def incomplete?
    status == false
  end

  def has_description?
    description.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  require "csv"

  before_action :set_task, except: [:index, :new, :create, :export_csv, :export_csv_form]

  def index
    fetch_possibly_filtered_tasks
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    respond_to do |format|
      if @task.persisted?
        format.html { redirect_to @task, notice: "Task successfully created!" }
        format.json { render json: @task.as_json(only: [:title, :due_date, :status]), status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: {errors: @task.errors.full_messages}, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      respond_to do |format|
        format.html do
          redirect_to @task, notice: "Task successfully updated!"
        end
        format.json { render json: @task.as_json(only: [:title, :due_date, :status]), status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: {errors: @task.errors.full_messages}, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "Task deleted"
  end

  def mark_task_as_done
    @task.update(status: true)
    redirect_to @task, notice: "Get it, girl!"
  end

  def export_csv_form
    render :export_csv_form
  end

  def export_csv
    start_date = params[:start_date]
    end_date = params[:end_date]

    if start_date.present? && end_date.present?
      start_date = Date.parse(start_date)
      end_date = Date.parse(end_date)
    else
      redirect_to export_csv_form_tasks_url, notice: "Please enter a start and end date"
      return
    end

    @tasks = Task.where("due_date >= ? AND due_date <= ?", start_date, end_date)

    # require "pry-remote"
    # binding.remote_pry

    if @tasks.any?
      respond_to do |format|
        format.csv do
          send_data generate_csv(@tasks), filename: "tasks.csv"
        end
      end
    else
      redirect_to export_csv_form_tasks_url, notice: "No tasks found in selected date range"
    end
  end

  private

  def generate_csv(tasks)
    CSV.generate(headers: true) do |csv|
      csv << ["Title", "Date Created", "Status"]

      @tasks.each do |task|
        csv << [
          task.title,
          formatted_date(task.created_at),
          task.status ? "completed" : "incomplete"
        ]
      end
    end
  end

  def fetch_possibly_filtered_tasks
    @tasks = if params[:status] == "completed"
      Task.completed
    elsif params[:status] == "incomplete"
      Task.incomplete
    else
      Task.all # With a lot of tasks in a production app, we would use pagination here
    end
  end

  def formatted_date(time)
    time.strftime("%Y-%m-%d")
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :due_date, :status, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def format_due_date(task)
    task.due_date.strftime("%m/%d/%Y")
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto flex flex-col">

    <div class="flash">
      <%= render "shared/flash" %>
    </div>
    <main class="flex-1">
      <%= yield %>
    </main>
    <div class="mx-auto my-4 text-sm text-center py-6">
    <p><%= debug(params) if Rails.env.development?%></p>
      Copyright <%= Date.current.year %> <%= link_to "Redrambles", "https://github.com/redrambles", class: "cursor-pointer decoration-1 underline-offset-4 hover:decoration-2" %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div
    class="flash-message <%= type %>"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>

  <% if task.errors.any? %>
    <div class="error-messages">
      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="space-y-12">
    <div class="border-b border-gray-900/10 pb-12">
      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="sm:col-span-3">
          <%= form.label :title, class:"block text-sm font-medium leading-6 text-gray-900"%>
          <div class="mt-2">
            <%= form.text_field :title, class:"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#7ee47e] sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="sm:col-span-3">
          <%= form.label :due_date, class:"block text-sm font-medium leading-6 text-gray-900"  %>
          <div class="mt-2">
            <%= form.date_field :due_date, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#7ee47e] sm:text-sm sm:leading-6" %>
          </div>
        </div>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-8 ">
        <div class="sm:col-span-3">
          <%= form.label :description, class:"block text-sm font-medium leading-6 text-gray-900"%>
          <div class="mt-2">
            <%= form.rich_text_area :description, rows: 4, placeholder: "Optional - 250 chars max!", maxlength: 250, class:"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#7ee47e] sm:text-sm sm:leading-6" %>
          </div>
        </div>
      </div>
      <div class="mt-2 space-y-10">
        <fieldset>
          <div class="mt-6 space-y-6">
            <div class="relative flex gap-x-3">
              <div class="flex h-6 items-center">
                <%= form.check_box :status, class: "h-4 w-4 rounded border-gray-300 text-[#7ee47e] focus:ring-[#7ee47e]" %>
              </div>
              <div class="text-sm leading-6">
                <%= form.label :completed, class: "font-medium text-gray-900" %>
              </div>
            </div>
          </div>
        </fieldset>
       </div>
      <%= form.submit class:"btn btn-success"  %>
     </div>
  <div>


<% end %>

app/views/tasks/edit.html.erb
<h1 class="my-4 py-2">Edit your Task</h1>

<%= render 'form', task: @task %>

<div class="flex flex-col sm:flex-row sm:gap-4">
  <%= link_to "Back to all tasks", tasks_url, class: "task-status btn btn-neutral" %>
  <%= link_to "Cancel", task_path(@task), class: "task-status btn btn-neutral" %>
</div>

app/views/tasks/export_csv_form.html.erb
<h1>Export Tasks to CSV File</h1>

<%= form_tag export_csv_tasks_path(format: :csv), method: :get do %>
  <div class="border-b border-gray-900/10 pb-12">
    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
      <div class="sm:col-span-3">
        <%= label_tag 'Start Date' %>
        <div class="mt-2">
          <%= text_field_tag 'start_date', nil, type: 'date', class:"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#7ee47e] sm:text-sm sm:leading-6"  %>
        </div>
      </div>

      <div class="sm:col-span-3">
        <%= label_tag 'End Date' %>
        <div class="mt-2">
          <%= text_field_tag 'end_date', nil, type: 'date', class:"block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-[#7ee47e] sm:text-sm sm:leading-6" %>
        </div>
      </div>
    </div>
    <%= submit_tag 'Export CSV', class: 'btn btn-success text-right block ml-auto' %>
  </div>
  <div class="mt-10">
    <%= link_to "Back to all tasks", tasks_url, class: "task-status btn btn-neutral no-underline" %>
  </div>

<% end %>

app/views/tasks/index.html.erb
<header class="task-header my-6 flex justify-between items-center">
  <h1 class="mb-0" >Tasks</h1>
  <div>
    <%= link_to "New Task", new_task_path, class:"btn btn-neutral" %>
    <% if @tasks.any? %>
      <%= link_to "Export CSV", export_csv_form_tasks_path, class:"btn btn-neutral"%>
    <% end %>
  </div>
</header>

<div class="flex flex-col sm:flex-row mt-10 sm:mt-20 sm:gap-4">
  <%= link_to 'Show Completed', tasks_path(status: 'completed'), class: "task-status btn btn-neutral #{ params[:status]&.include?('completed') && 'is-active' }" %>
  <%= link_to 'Show ToDo', tasks_path(status: 'incomplete'), class: "task-status btn btn-neutral #{ params[:status]&.include?('incomplete') && 'is-active' }" %>
  <%= link_to 'Show All Tasks', tasks_path, class: "task-status btn btn-neutral #{ params[:status].blank? && 'is-active' }" %>
</div>


<% if @tasks.any? %>

  <ul class="px-0 pb-10">
    <% @tasks.each do |task| %>
    <div class="tasks <%= task.completed? ? 'completed' : 'incomplete' %> py-1 px-4 mb-4">
    <div class="flex justify-between items-center my-6">
      <h2 class="my-0"><%= link_to task.title, task, class: "cursor-pointer decoration-1 underline-offset-4 hover:decoration-2" %></h2>
      <%= button_to heroicon('trash'), task_path(task), method: :delete, data: { turbo_confirm: "Are you sure?" } %>
    </div>
      <p class="text-sm"><%= format_due_date(task) %></p>
      <% if task.has_description? %>
        <p class="text-right"><%= task.description %></p>
      <% end %>
    </div>
    <% end%>
  </ul>

<% else %>

  <p> No tasks yet. Create one!

<% end%>

app/views/tasks/new.html.erb
<h1 class="my-4 py-2">Create your task!</h1>

  <%= render 'form', task: @task %>

  <%= link_to "Back to All Tasks", tasks_path, class: "btn btn-neutral " %>

app/views/tasks/show.html.erb
<h1 class="my-4 py-2"><%= @task.title %></h1>
<p><%= @task.description %></p>
<p><%= format_due_date(@task) %></p>

<% if @task.incomplete? %>
  <div class="flex gap-2">
    <%= button_to complete_task_path(@task), class:"cursor-pointer flex gap-2 items-center btn btn-success" do %>
      Mark done <%= heroicon('check-circle') %>
    <% end %> 
  </div>
<% end %>


<div class="flex flex-col sm:flex-row sm:gap-4 mt-10">
  <%= link_to "Back to all tasks", tasks_url, class: "task-status btn btn-neutral" %>
  <%= link_to "Edit task", edit_task_path(@task), class: "task-status btn btn-neutral" %>
  <%= button_to "Delete Task", task_path(@task), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "task-status btn btn-danger" %>
</div>